export const tableItems = [
  // Starter
  { item_name: 'Turkey',         station: 'Starter' },
  { item_name: 'Ham',            station: 'Starter' },
  { item_name: 'Italian Meat',   station: 'Starter' },
  { item_name: 'Pepper Jack',    station: 'Starter' },
  { item_name: 'Provolone',      station: 'Starter' },
  { item_name: 'Cheddar',        station: 'Starter' },
  { item_name: 'Peppers',        station: 'Starter' },
  { item_name: 'Onions',         station: 'Starter' },
  { item_name: 'Mayo',           station: 'Starter' },
  { item_name: 'Burger Patties', station: 'Starter' },
  // Finisher A
  { item_name: 'Fried Eggs',             station: 'Finisher A' },
  { item_name: 'Spicy Chicken',          station: 'Finisher A' },
  { item_name: 'Homestyle Chicken',      station: 'Finisher A' },
  { item_name: 'Wings',                  station: 'Finisher A' },
  { item_name: 'Premium Chicken',        station: 'Finisher A' },
  { item_name: 'Pork Sausage',           station: 'Finisher A' },
  { item_name: 'Scrambled Egg Patties',  station: 'Finisher A' },
  { item_name: 'Bacon',                  station: 'Finisher A' },
  { item_name: 'Steak',                  station: 'Finisher A' },
  { item_name: 'Shredded Chicken',       station: 'Finisher A' },
  { item_name: 'Shredded Cheddar',       station: 'Finisher A' },
  { item_name: 'Shredded Mozz',          station: 'Finisher A' },
  { item_name: 'Scrambled Egg Mix',      station: 'Finisher A' },
  { item_name: 'Rice & Beans',           station: 'Finisher A' },
  { item_name: 'Parmesan',               station: 'Finisher A' },
  { item_name: 'Pepperoni',              station: 'Finisher A' },
  { item_name: 'Sausage Crumbles',       station: 'Finisher A' },
  // Finisher B
  { item_name: 'Romaine',           station: 'Finisher B' },
  { item_name: 'Pickles',           station: 'Finisher B' },
  { item_name: 'Guac',              station: 'Finisher B' },
  { item_name: 'Tomatoes',          station: 'Finisher B' },
  { item_name: 'Jalapenos',         station: 'Finisher B' },
  { item_name: 'Red Onions',        station: 'Finisher B' },
  { item_name: 'Pico',              station: 'Finisher B' },
  { item_name: 'Diced Onions',      station: 'Finisher B' },
  { item_name: 'Mild Pepper Rings', station: 'Finisher B' },
  { item_name: 'American Cheese',   station: 'Finisher B' },
  { item_name: 'Lettuce',           station: 'Finisher B' },
]
