export const inventoryItems = [
  // Bread
  { item_name: 'White Sub Roll',               build_to: 'Bread', category: 'Bread', amount_needed: 7  },
  { item_name: 'Wheat Sub Roll',               build_to: 'Bread', category: 'Bread', amount_needed: 2  },
  { item_name: 'Pretzel Sub Roll',             build_to: 'Bread', category: 'Bread', amount_needed: 2  },
  { item_name: 'Sourdough',                    build_to: 'Bread', category: 'Bread', amount_needed: 1  },
  { item_name: 'Plain Bagel',                  build_to: 'Bread', category: 'Bread', amount_needed: 3  },
  { item_name: 'Everything Bagel',             build_to: 'Bread', category: 'Bread', amount_needed: 2  },
  { item_name: 'Tortillas (Whole)',             build_to: 'Bread', category: 'Bread', amount_needed: 6  },
  { item_name: 'Tortillas (Half)',              build_to: 'Bread', category: 'Bread', amount_needed: 1  },
  { item_name: 'Slider Buns',                  build_to: 'Bread', category: 'Bread', amount_needed: 1  },
  { item_name: 'Flatbread',                    build_to: 'Bread', category: 'Bread', amount_needed: 3  },
  { item_name: 'Burger Buns',                  build_to: 'Bread', category: 'Bread', amount_needed: 4  },
  { item_name: 'English Muffins',              build_to: 'Bread', category: 'Bread', amount_needed: 1  },
  { item_name: 'Biscuits',                     build_to: 'Bread', category: 'Bread', amount_needed: 1  },
  { item_name: 'Croissants',                   build_to: 'Bread', category: 'Bread', amount_needed: 1  },
  { item_name: 'Waffles (bags of 8)',          build_to: 'Bread', category: 'Bread', amount_needed: 3  },
  { item_name: 'Soft Pretzels (tubs of 6)',    build_to: 'Bread', category: 'Bread', amount_needed: 2  },
  { item_name: 'Jr Pretzel Rolls (Bags of 6)', build_to: 'Bread', category: 'Bread', amount_needed: 2  },
  { item_name: 'Pretzel Hot Dogs (Bags of 8)', build_to: 'Bread', category: 'Bread', amount_needed: 2  },
  { item_name: 'Taco Tortillas',               build_to: 'Bread', category: 'Bread', amount_needed: 4  },
  // Prep
  { item_name: 'FroYo',                              build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Peach Puree',                        build_to: 'Prep', category: 'Prep', amount_needed: 3  },
  { item_name: 'Strawberry Puree',                   build_to: 'Prep', category: 'Prep', amount_needed: 12 },
  { item_name: 'Banana Puree',                       build_to: 'Prep', category: 'Prep', amount_needed: 3  },
  { item_name: 'Pina Colada Puree',                  build_to: 'Prep', category: 'Prep', amount_needed: 3  },
  { item_name: 'Chili',                              build_to: 'Prep', category: 'Prep', amount_needed: 1  },
  { item_name: 'Burgers (Cambro of Pack)',            build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Fried Eggs',                         build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Scrambled Eggs (Cambro of 40)',       build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Pork Sausage (Cambro of 40-80)',      build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Western Burrito (Bag of 8)',          build_to: 'Prep', category: 'Prep', amount_needed: 1  },
  { item_name: 'Sausage Burrito (Bag of 8)',          build_to: 'Prep', category: 'Prep', amount_needed: 1  },
  { item_name: 'Bacon Burrito (Bag of 8)',            build_to: 'Prep', category: 'Prep', amount_needed: 1  },
  { item_name: 'Chicken Sausage (Bag of 10)',         build_to: 'Prep', category: 'Prep', amount_needed: 3  },
  { item_name: 'Egg Whites (Bag of 10)',              build_to: 'Prep', category: 'Prep', amount_needed: 3  },
  { item_name: 'Scrambled Egg Mix (Bag)',             build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Guacamole',                          build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Premium Chicken',                    build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Homestyle Chicken',                  build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Spicy Chicken',                      build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Taco Chicken (Bag)',                 build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Rice & Beans (Bag)',                 build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Wings (Bag)',                        build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Italian Sausage (Bag)',              build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Bratwurst (Bag)',                    build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Pork Stickers (Bag)',                build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Taco Beef (Bag)',                    build_to: 'Prep', category: 'Prep', amount_needed: 1  },
  { item_name: 'Brisket (Bag)',                      build_to: 'Prep', category: 'Prep', amount_needed: 1  },
  { item_name: 'Peppers (Cambro)',                   build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Onions (Cambro)',                    build_to: 'Prep', category: 'Prep', amount_needed: 2  },
  { item_name: 'Breakfast Sandwiches (Box)',         build_to: 'Prep', category: 'Prep', amount_needed: 1  },
  { item_name: 'Steak (Bag)',                        build_to: 'Prep', category: 'Prep', amount_needed: 3  },
  { item_name: 'Slider Patties (Bag of 10)',         build_to: 'Prep', category: 'Prep', amount_needed: 3  },
  { item_name: 'Tenders (Bag)',                      build_to: 'Prep', category: 'Prep', amount_needed: 4  },
  { item_name: 'Boneless Bites (Bag)',               build_to: 'Prep', category: 'Prep', amount_needed: 4  },
]
